from __future__ import annotations

from typing import Any, Dict

from core.migrations.types import MigrationOutcome


LATEST_APP_STATE_SCHEMA_VERSION = 1


def _as_int(v: Any, default: int) -> int:
    try:
        if v is None:
            return default
        if isinstance(v, bool):
            return int(v)
        return int(v)
    except Exception:
        return default


def _as_dict(v: Any) -> Dict[str, Any]:
    return v if isinstance(v, dict) else {}


def migrate_app_state_json(data: Dict[str, Any]) -> MigrationOutcome:
    """
    app_state.json migrations
    Current latest: v1

    Worker ID policy (IMPORTANT):
    - worker_id == 0 is VALID.
    - Missing worker_id means "unset" and will be generated by AppStateRepo.
    - If worker_id exists but is invalid/out of range, remove it so repo can regenerate.

    Also normalizes window section.
    """
    if not isinstance(data, dict):
        data = {}

    from_ver = _as_int(data.get("schema_version", 1), 1)
    changed = False

    if "schema_version" not in data or from_ver != LATEST_APP_STATE_SCHEMA_VERSION:
        data["schema_version"] = LATEST_APP_STATE_SCHEMA_VERSION
        changed = True

    # normalize window dict
    if "window" not in data or not isinstance(data.get("window"), dict):
        data["window"] = _as_dict(data.get("window"))
        changed = True

    win = _as_dict(data.get("window"))
    # ensure numeric types if present
    for k in ("width", "height", "x", "y"):
        if k in win:
            v = win.get(k)
            if v is None:
                continue
            try:
                win[k] = int(v)
            except Exception:
                # drop invalid coordinate
                win.pop(k, None)
                changed = True
    data["window"] = win

    # worker_id validation (0..1023 valid)
    if "worker_id" in data:
        wid = data.get("worker_id")
        try:
            wid_i = int(wid)
            if wid_i < 0 or wid_i > 1023:
                data.pop("worker_id", None)
                changed = True
            else:
                # normalize type to int
                if not isinstance(wid, int):
                    data["worker_id"] = wid_i
                    changed = True
        except Exception:
            data.pop("worker_id", None)
            changed = True

    # last_profile normalize to str if present
    if "last_profile" in data and not isinstance(data.get("last_profile"), str):
        try:
            data["last_profile"] = str(data.get("last_profile", ""))
        except Exception:
            data["last_profile"] = ""
        changed = True

    return MigrationOutcome(
        data=data,
        changed=changed,
        from_version=from_ver,
        to_version=int(data.get("schema_version", LATEST_APP_STATE_SCHEMA_VERSION)),
    )